const SUPABASE_URL = "https://aqvcalymmxqwadipbzwg.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxdmNhbHltbXhxd2FkaXBiendnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwODA3NzcsImV4cCI6MjA4NjY1Njc3N30.2pTQWjTD7OeEoA4DXPLqfAVvB6u_DedLVJvyxrTSpHA";

window.supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
