"use strict";
const client = window.supabaseClient;
const $ = (id)=>document.getElementById(id);
function rupiah(v){return "Rp " + Number(v||0).toLocaleString("id-ID")}
function dateID(v){if(!v)return"-";const d=new Date(v);return isNaN(d)?"-":d.toLocaleString("id-ID",{day:"2-digit",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"})}
function titleize(v){return String(v||"-").replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase())}
function paymentLabel(v){const x=String(v||"").toLowerCase();if(x==="lunas")return"LUNAS";if(x==="sebagian"||x==="dp")return"SEBAGIAN";if(x==="refund")return"REFUND";return"BELUM LUNAS"}
function paymentClass(v){const x=String(v||"").toLowerCase();if(x==="lunas")return"paid";if(x==="sebagian"||x==="dp")return"partial";return"unpaid"}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function showInvalid(msg){$("loadingState").classList.add("hidden");$("validState").classList.add("hidden");$("invalidMessage").textContent=msg||"Invoice tidak dapat diverifikasi.";$("invalidState").classList.remove("hidden")}
function render(data){const o=data.order||{};$("invoiceNumber").textContent=o.order_number||(`ORD-${String(o.id||0).padStart(5,"0")}`);$("invoiceDate").textContent=dateID(o.created_at);$("customerName").textContent=o.customer_name||"-";$("customerPhone").textContent=o.customer_whatsapp||"-";$("paymentMethod").textContent=titleize(o.payment_method);$("orderStatus").textContent=titleize(o.order_status);$("paymentStatus").textContent=paymentLabel(o.payment_status);$("paymentStatus").className=`status-pill ${paymentClass(o.payment_status)}`;$("grandTotal").textContent=rupiah(o.total);
 const items=Array.isArray(o.items)?o.items:[];$("productList").innerHTML=items.length?items.map(it=>`<div class="product-item"><div class="product-top"><div><div class="product-name">${esc(it.product_name||"-")}</div><div class="product-meta">${[it.variant_name,it.ram&&`RAM ${it.ram}`,it.storage&&`Storage ${it.storage}`,it.color].filter(Boolean).map(esc).join(" · ")||"Varian standar"}<br>Qty ${Number(it.quantity||0)}</div></div><div class="product-price">${rupiah(it.subtotal)}</div></div></div>`).join(""):"<div class='product-item'>Tidak ada detail produk.</div>";
 const units=Array.isArray(o.units)?o.units:[];if(units.length){$("unitSection").classList.remove("hidden");$("unitList").innerHTML=units.map((u,i)=>`<div class="unit-item"><div class="unit-field"><small>Unit</small><b>${esc(u.product_name||`Unit ${i+1}`)}</b></div><div class="unit-field"><small>IMEI</small><b>${esc(u.imei_masked||"-")}</b></div><div class="unit-field"><small>Serial</small><b>${esc(u.serial_masked||"-")}</b></div></div>`).join("")}
 $("loadingState").classList.add("hidden");$("invalidState").classList.add("hidden");$("validState").classList.remove("hidden")}
async function load(){const q=new URLSearchParams(location.search);const id=Number(q.get("id")||0);const no=(q.get("no")||"").trim();if(!id||!no)return showInvalid("Tautan verifikasi tidak lengkap.");const {data,error}=await client.rpc("verify_product_invoice",{p_order_id:id,p_order_number:no});if(error){console.error(error);return showInvalid("Gagal memverifikasi invoice. Silakan coba lagi.")}if(!data?.success)return showInvalid(data?.message||"Invoice tidak ditemukan.");render(data)}
document.addEventListener("DOMContentLoaded",load);
